name: Plugin Support
description: I want to suggest a plugin to be properly supported in Primary Simplified
labels: ["🔌 plugin support"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this plugin support/compatibility report! Use the Enhancement form instead for feature or additional Style Settings suggestions.
  - type: input
    id: primary-version
    attributes:
      label: Primary Simplified Version
      description: What version of Primary Simplified are you using? Check `manifest.json` in the theme folder or the theme information shown under `Settings` → `Appearance` → `Themes`.
      placeholder: e.g. 2.10.0
    validations:
      required: true
  - type: input
    id: plugin-name
    attributes:
      label: What Community Plugin do you want to get Supported?
      placeholder: e.g. Style Settings
    validations:
      required: true
  - type: input
    id: plugin-link
    attributes:
      label: Please add the link to the Community Plugin
      description: To get the link to the Community Plugin, go the plugin's page in Community Plugins inside Obsidian, then press `Copy share link`. Paste the link below.
      placeholder: e.g. obsidian://show-plugin?id=obsidian-style-settings
    validations:
      required: true
  - type: textarea
    id: plugin-info
    attributes:
      label: Do you have any specifics to share?
      description: If you have specific compatibility requirements, list them below. If the current design is incorrect, share screenshots of the plugin with Primary Simplified and with Obsidian's default theme.
